trigger:
- master

pool:
  vmImage: 'windows-2019'
stages:
- stage: 'Build'
  displayName: 'Build the simpleapi docker image'
  jobs:
   - job: Build
     steps:
       - task: Docker@2
         inputs:
           containerRegistry: 'cicdacr'
           repository: 'modernapi'
           command: 'buildAndPush'
           Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
           tags: |
             $(Build.BuildId)
             Latest
